In [ ]:
import numpy as np
!pip install numpy
hj=np.array([1.1,2.2,3.3,4.4,5.5])
print("hj",hj)

hj [1.1 2.2 3.3 4.4 5.5]


In [ ]:
a3= np.array([1. ,2. , 3.3])
a3

array([1. , 2. , 3.3])

In [ ]:
array([1. ,2. , 3.3])

NameError: name 'array' is not defined

In [ ]:
a4= np.array([1,2,3.3, "hi"])
a4

array(['1', '2', '3.3', 'hi'], dtype='<U32')

In [ ]:
a5= np.array([1,2,3.3],'int')
a5

array([1, 2, 3])

In [ ]:
a6= np.array([1,2,3.3],'float')
a6

array([1. , 2. , 3.3])

In [ ]:
l1= [1,2,3,4]
l1= np.array([l1])

In [ ]:
#Array operators
#nd
a4.size

4

In [ ]:
#shape

a3.shape

(3,)

In [ ]:
#2d array
# syntax :np.array([[]])

In [ ]:
array([[1,2,3,4,5]])

NameError: name 'array' is not defined

In [ ]:
a7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a6 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3,4,5]])
a6

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
a6.size

9

In [ ]:
a7.ndim

2

In [ ]:
a6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a6.ndim

2

In [ ]:
a8 = np.((3,3))
a8

SyntaxError: invalid syntax (<ipython-input-36-f3b115d35082>, line 1)